let  a = 66;
let  b = 44;
console.log("swaping before value");
console.log("a = "+a);
console.log("b = "+b);
a = a+b;
b = a-b;
a = a-b;
console.log("swaping after value");
console.log("a = "+a);
console.log("b = "+b);